"""
**AveyTense Functions**

Availability: >= 0.3.68 \\
© 2024-Present Aveyzan // License: MIT \\
https://aveyzan.xyz/aveytense#aveytense.functions

Ports class methods of `Tense` and `Math` as functions. Unlike all other modules in `aveytense` module, this one must be imported within the `import` statement.
"""

from aveytense import Tense, Math

### 0.3.68

# Math
abs = Math.abs
acos = Math.acos
acosec = Math.acosec
acosech = Math.acosech
acosh = Math.acosh
acot = Math.acot
acoth = Math.acoth
acovercos = Math.acovercos
acoversin = Math.acoversin
addPercentage = Math.addPercentage
aexcosec = Math.aexcosec
aexsec = Math.aexsec
ahacovercos = Math.ahacovercos
ahacoversin = Math.ahacoversin
ahavercos = Math.ahavercos
ahaversin = Math.ahaversin
asec = Math.asec
asech = Math.asech
asin = Math.asin
asinh = Math.asinh
atan = Math.atan
atanh = Math.atanh
avercos = Math.avercos
aversin = Math.aversin
cbrt = Math.cbrt
cos = Math.cos
cosec = Math.cosec
cosech = Math.cosech
cosh = Math.cosh
covercos = Math.covercos
coversin = Math.coversin
cube = Math.cube
cubeCentered = Math.cubeCentered
decagonal = Math.decagonal
decagonalCentered = Math.decagonalCentered
diagonals = Math.diagonals
dodecagonal = Math.dodecagonal
dodecagonalCentered = Math.dodecagonalCentered
dodecahedral = Math.dodecahedral
dodecahedralCenetered = Math.dodecahedralCentered
excosec = Math.excosec
exsec = Math.exsec
fact = Math.fact
factFalling = Math.factFalling
factRising = Math.factRising
fib = Math.fib
fma = Math.fma
gcd = Math.gcd
hacovercos = Math.hacovercos
hacoversin = Math.hacoversin
havercos = Math.havercos
haversin = Math.haversin
hendecagonal = Math.hendecagonal
hendecagonalCentered = Math.hendecagonalCentered
heptagonal = Math.heptagonal
heptagonalCentered = Math.hendecagonalCentered
hexagonal = Math.hexagonal
hexagonalCentered = Math.hexagonalCentered
icosahedral = Math.icosahedral
icosahedralCentered = Math.icosahedralCentered
isComposite = Math.isComposite
isConstant = Math.isConstant
isDecimal = Math.isDecimal
isDecreasing = Math.isDecreasing
isFraction = Math.isFraction
isInRange = Math.isInRange
isIncreasing = Math.isIncreasing
isMonotonous = Math.isMonotonous
isNonDecreasing = Math.isNonDecreasing
isNonIncreasing = Math.isNonIncreasing
isNegative = Math.isNegative
isNumber = Math.isNumber
isPositive = Math.isPositive
isPrime = Math.isPrime
lcm = Math.lcm
ln = Math.ln
log = Math.log
log2 = Math.log2
log3 = Math.log3
log5 = Math.log5
log7 = Math.log7
log10 = Math.log10
lwdp = Math.lwdp
maxDigit = Math.maxDigit
mean = Math.mean
minDigit = Math.minDigit
nonagonal = Math.nonagonal
nonagonalCentered = Math.nonagonalCentered
octagonal = Math.octagonal
octagonalCentered = Math.octagonalCentered
octahedral = Math.octahedral
octahedralCentered = Math.octahedralCentered
pentagonal = Math.pentagonal
pentagonalCentered = Math.pentagonalCentered
pentatope = Math.pentatope
perm = Math.perm
polygonal = Math.polygonal
polygonalCentered = Math.polygonalCentered
pow = Math.pow
pronic = Math.pronic
pyramidal = Math.pyramidal
sec = Math.sec
sech = Math.sech
sin = Math.sin
sinh = Math.sinh
sqrt = Math.sqrt
square = Math.square
squareCentered = Math.squareCentered
star = Math.star
stdev = Math.stdev
stellaOctangula = Math.stellaOctangula
tan = Math.tan
tanh = Math.tanh
tetrahedral = Math.tetrahedral
tetrahedralCentered = Math.tetrahedralCentered
toDegrees = Math.toDegrees
toDigits = Math.toDigits
toGradians = Math.toGradians
toRadians = Math.toRadians
toScientific = Math.toScientific
triangular = Math.triangular
triangularCentered = Math.triangularCentered
tridecagonal = Math.tridecagonal
tridecagonalCentered = Math.tridecagonalCentered
trunc = Math.trunc
vercos = Math.vercos
versin = Math.versin

# Tense
abroadConvect = Tense.abroadConvect
abroadInside = Tense.abroadInside
abroadNegative = Tense.abroadNegative
abroadNegativeFlip = Tense.abroadNegativeFlip
abroadPack = Tense.abroadPack
abroadPositive = Tense.abroadPositive
abroadPositiveFlip = Tense.abroadPositiveFlip
abroadPrecede = Tense.abroadPrecede
abroadSplit = Tense.abroadSplit
abroadSufcede = Tense.abroadSufcede
all = Tense.all
any = Tense.any
append = Tense.append
architecture = Tense.architecture
asyncGenerator = Tense.asyncGenerator
bin = Tense.bin # 0.3.71
cast = Tense.cast
chr = Tense.chr # 0.3.71
clear = Tense.clear
copy = Tense.copy
deepcopy = Tense.deepcopy
difference = Tense.difference
dis = Tense.dis
endsWith = Tense.endsWith
equal = Tense.equal
exclude = Tense.exclude
expect = Tense.expect
explode = Tense.explode
extend = Tense.extend
extract = Tense.extract
first = Tense.first
flatten = Tense.flatten
generator = Tense.generator
getAllItemTypes = Tense.getAllItemTypes
getAttr = Tense.getAttr
getAttrs = Tense.getAttrs # 0.3.74
getFlags = Tense.getFlags
getGeneric = Tense.getGeneric
group = Tense.group
hasAttr = Tense.hasAttr
hasAttrs = Tense.hasAttrs # 0.3.74
hex = Tense.hex # 0.3.71
improvedBogoSort = Tense.improvedBogoSort
inequal = Tense.inequal
isAbroad = Tense.isAbroad
isArray = Tense.isArray
isAsyncGenerator = Tense.isAsyncGenerator
isAwaitable = Tense.isAwaitable
isBinary = Tense.isBinary
isBool = Tense.isBool
isBoolean = Tense.isBoolean
isByteArray = Tense.isByteArray
isBytes = Tense.isBytes
isClass = Tense.isClass
isComplex = Tense.isComplex
isCoroutine = Tense.isCoroutine
isDeprecated = Tense.isDeprecated
isDeque = Tense.isDeque
isDict = Tense.isDict
isEllipsis = Tense.isEllipsis
isFinalClass = Tense.isFinalClass
isFinalProperty = Tense.isFinalProperty
isFloat = Tense.isFloat
isFrozenSet = Tense.isFrozenSet
isFunction = Tense.isFunction
isGenerator = Tense.isGenerator
isGeneric = Tense.isGeneric
isHexadecimal = Tense.isHexadecimal
isIn = Tense.isIn
isInt = Tense.isInt
isInteger = Tense.isInteger
isIterable = Tense.isIterable
isIterator = Tense.isIterator
isLambda = Tense.isLambda
isList = Tense.isList
isMemoryView = Tense.isMemoryView
isNone = Tense.isNone
isNumeric = Tense.isNumeric
isOctal = Tense.isOctal
isProperty = Tense.isProperty
isSet = Tense.isSet
isSlice = Tense.isSlice
isSpecialForm = Tense.isSpecialForm
isStr = Tense.isStr
isString = Tense.isString
isTuple = Tense.isTuple
isTuple2 = Tense.isTuple2
isType = Tense.isType
isUnbound = Tense.isUnbound # experimental
isUnion = Tense.isUnion
last = Tense.last
license = Tense.license
occurrences = Tense.occurrences
oct = Tense.oct # 0.3.71
ord = Tense.ord # 0.3.71
pick = Tense.pick
print = Tense.print
probability = Tense.probability
probability2 = Tense.probability2
probability3 = Tense.probability3
random = Tense.random
randomString = Tense.randomString
removePrefix = Tense.removePrefix
removeSuffix = Tense.removeSuffix
replace = Tense.replace
reverse = Tense.reverse
shuffle = Tense.shuffle
sleep = Tense.sleep
splitGeneric = Tense.splitGeneric
splitUnion = Tense.splitUnion # 0.3.74
startsWith = Tense.startsWith
test = Tense.test
timeit = Tense.timeit
toList = Tense.toList
tryOrPass = Tense.tryOrPass
tryOrReturn = Tense.tryOrReturn
until = Tense.until
union = Tense.union

del Math, Tense

__all__ = [k for k in globals() if not k.startswith("_")]